Remove invalid timed run on luna pipeline
This fixes an error that shows up in Manage Old Data:

    ConversionException: Failed calling method ---- Debugging information ---- message : Failed calling method cause-exception : java.io.InvalidObjectException cause-message : Invalid input: "H 23 * * Wed": line 1:10: unexpected char: 'W' method : hudson.triggers.TimerTrigger.readResolve() class : hudson.triggers.TimerTrigger required-type : hudson.triggers.TimerTrigger converter-type : hudson.util.RobustReflectionConverter path : /flow-definition/properties/org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty/triggers/hudson.triggers.TimerTrigger line number : 287 -------------------------------